//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3082
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShiptalkWeb.User.Admin {
    
    
    public partial class DesignateUserApprover {
        
        /// <summary>
        /// dv3colFormContent control.
        /// </summary>
        /// <remarks>
        /// Auto-generated Descriptors.
        /// To modify move Descriptors declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl dv3colFormContent;
    }
}
